sudo apt update
sudo apt install -y nginx
sudo systemctl enable --now nginx
sudo systemctl status nginx


sudo nginx -t          # проверка синтаксиса, не применяет изменения
sudo systemctl reload nginx    # применяет без разрыва текущих соединений

ln -s /etc/nginx/sites-available/000-default.conf /etc/nginx/sites-enabled/
ls -la /etc/nginx/sites-enabled/  # проверить

# ssl

apt install -y certbot python3-certbot-nginx

certbot --nginx -d domain.com


sudo certbot certificates
посмотреть сертификаты


sudo certbot renew
обновить вске сертификаты
