# mypy.ini
[mypy]
exclude = manage\.py|migrations|_temp/|/scripts/.*/x(_.*)?\.py$
strict = true
plugins = mypy_django_plugin.main

[mypy-constance.*]
ignore_missing_imports = true

[mypy-celery.*]
ignore_missing_imports = true

[mypy.plugins.django-stubs]
django_settings_module = "config.settings"

[mypy-*.factories]
disable_error_code = var-annotated,attr-defined,no-untyped-call,untyped-decorator