[project]
name = "backoffice"
version = "0.0.1"
requires-python = ">=3.12"

[tool.ruff]
line-length = 119
exclude = ["_temp", ".venv", "migrations"]

[tool.ruff.lint]
fixable = ["ALL"]
select = ["ALL"]
ignore = [
  "COM819",
  "ANN204",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "FA102",
  "RUF001",  # ambiguous-unicode-character-string
  "PERF203", # try-except-in-loop
  "D203",    # incorrect-blank-line-before-class
  "D213",    # multi-line-summary-second-line
  "S311",    # suspicious-non-cryptographic-random-usage
  "EM101",   # raw-string-in-exception
  "TRY003",  # raise-vanilla-args
  "EM102",   # f-string-in-exception
  "TC006",   # runtime-cast-value
  "LOG015",
  "TD002",   # todo author
  "TD003",   # todo link
  "FIX002",  # allow todo
]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["ALL"]
"manage.py" = ["ALL"]
"app/_temp/*.py" = ["ALL"]
".venv/**" = ["ALL"]
"**/views.py" = [
  "A002",    # builtin-argument-shadowing
]
"**/test_*.py" = [
  "PT027",   # self.assertRaises
  "PLR2004", # magic-value-comparison
  "PT004",
  "S101",    # assert
  "SLF001",  # private-member-access
  "DTZ001",  # datetime() without tzinfo
  "FBT001",  # boolean positional argument
]
"**/conftest.py" = [
  "FBT001",  # boolean-type-hint-positional-argument
  "FBT002",  # boolean-default-value-positional-argument
  "PLR0913", # too-many-arguments
]
"**/scripts/*.py" = [
  "T201",    # print
  "T203",    # pprint
]
"**/scripts/**/x.py" = ["ALL"]
"**/scripts/**/x_*.py" = ["ALL"]
"**/tests/**/factories.py" = [
  "FBT001",  # boolean positional argument
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false